# Generated by Django 6.1 on 2026-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('oldprice', models.FloatField(blank=True, db_column='oldPrice', null=True)),
                ('description', models.TextField()),
                ('images', models.TextField(blank=True, null=True)),
                ('category', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviewscount', models.IntegerField(blank=True, db_column='reviewsCount', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('badge', models.TextField()),
                ('totaldiscount', models.FloatField(db_column='totalDiscount')),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
    ]
